import { Unit } from '@/types';

export const units: Unit[] = [
  {
    id: 'introduction',
    title: '🇫🇷 Introduction',
    description: 'Basic greetings, numbers, alphabet, and classroom vocabulary',
    topics: [
      'Greetings (Formal & Informal)',
      'Numbers 0-20',
      'French Alphabet',
      'Classroom Rules & Vocabulary',
      'Days of the Week',
      'Basic Conversation Phrases',
      'French Culture & Geography',
      'Titles (Monsieur, Madame)',
      'School Supplies Vocabulary',
    ],
  },
  {
    id: 'unit-2',
    title: '🇫🇷 Unit 2',
    description: 'Activities, food, verb conjugation, and adverbs',
    topics: [
      'Olympic Sports Vocabulary',
      'Activities (J\'aime/Je n\'aime pas)',
      'Food Vocabulary',
      'Days of the Week',
      'Subject Pronouns (je, tu, il/elle, nous, vous, ils/elles)',
      'Tu vs. Vous',
      '-ER Verb Conjugation',
      'Common Verbs (parler, chanter, danser, manger, jouer)',
      'Adverbs (un peu, bien, beaucoup)',
      'Gender of Nouns (le, la, les)',
      'Definite Articles',
      'Preferences (préférer)',
      'Negation (ne...pas)',
      'Nationalities',
      'Classroom Expressions',
    ],
  },
  {
    id: 'unit-3',
    title: '🇫🇷 Unit 3',
    description: 'Classroom objects, numbers, prepositions, and key verbs',
    topics: [
      'Classroom Vocabulary (objects)',
      'Numbers 20-100',
      'Prepositions (sous, sur, derrière)',
      'Face & Body Parts Vocabulary',
      'Indefinite Articles (un, une, des)',
      'Verb: Avoir (to have)',
      'Verb: Être (to be)',
      'Negation Review',
      'School Subjects',
      'Telling Time (Quelle heure est-il?)',
      'Christmas Vocabulary',
      'Questions with est-ce que',
      'Combining Sentences (qui, quand, où)',
      'Location Vocabulary (en ville, à la cantine, etc.)',
    ],
  },
];
