/**
 * Centralized configuration for pipeline scripts.
 */

export const MODELS = {
  pdfConversion: 'claude-sonnet-4-20250514',
  topicExtraction: 'claude-sonnet-4-20250514',
  topicSimilarity: 'claude-haiku-4-5-20251001',
  /** MCQ and true-false generation (structured types with fixed answer sets) */
  questionGenerationStructured: 'claude-haiku-4-5-20251001',
  /** Fill-in-blank and writing generation (typed answers requiring higher accuracy) */
  questionGenerationTyped: 'claude-sonnet-4-5-20250929',
  /** Post-generation answer validation + acceptable variation generation */
  answerValidation: 'claude-sonnet-4-5-20250929',
  /** Cross-validation audit (Mistral Large) */
  mistralAudit: 'mistral-large-latest',
};

export type QuestionType = 'multiple-choice' | 'fill-in-blank' | 'true-false' | 'writing';

/** Types generated by the structured (cheaper) model */
export const STRUCTURED_TYPES: QuestionType[] = ['multiple-choice', 'true-false'];
/** Types generated by the typed-answer (higher-quality) model */
export const TYPED_TYPES: QuestionType[] = ['fill-in-blank', 'writing'];

/** Returns the appropriate generation model for a given question type */
export function getModelForType(type: QuestionType): string {
  return STRUCTURED_TYPES.includes(type)
    ? MODELS.questionGenerationStructured
    : MODELS.questionGenerationTyped;
}

/** Estimated cost per Haiku 4.5 API call (~3k input + 1.5k output tokens) */
export const COST_PER_API_CALL = 0.008;
